/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package KeyGenSignTool;

//import java.util.*;
import javax.swing.*;
//import javax.swing.event.*;

public class App {
    public int CreateForm() {
        JFrame Form1 = new JFrame("MY SECOND JFRAME");
        JPanel Panel1 = new JPanel();
        JLabel Text = new JLabel("Sample text");
        Form1.setDefaultCloseOperation(3);
        Panel1.setSize(300, 300);
        Form1.setSize(300, 300);

        Form1.setVisible(true);
        Form1.add(Panel1);
        Panel1.add(Text);
        return 1;

    }

    public static void main(String[] args) {
        App InitializeCreation = new App();
        InitializeCreation.CreateForm();
    }
}