/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package KeyGenSignTool;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appCreatedJframe() {
        App classUnderTest = new App();

        assertSame(1, classUnderTest.CreateForm());
        // assert not null it scans the output of the return value if null the test fail
        // else the test pass
    }

}
